FROM golang:1.25-alpine AS build

WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY internals ./internals
COPY cmd ./cmd

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o gateway-app ./cmd/gateway/main.go

FROM alpine:3.20

WORKDIR /app
RUN apk add --no-cache ca-certificates

COPY --from=build /app/gateway-app /app/gateway-app

EXPOSE 50050
CMD ["/app/gateway-app"]