# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/common.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protobuf/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protobuf/common.proto\x12\x0eListeningParty*2\n\nRoomStatus\x12\n\n\x06\x41\x43TIVE\x10\x00\x12\x0c\n\x08INACTIVE\x10\x01\x12\n\n\x06\x43LOSED\x10\x02*)\n\x0eRoomVisibility\x12\n\n\x06PUBLIC\x10\x00\x12\x0b\n\x07PRIVATE\x10\x01*:\n\x0eRoomMemberRole\x12\x08\n\x04HOST\x10\x00\x12\r\n\tMODERATOR\x10\x01\x12\x0f\n\x0bPARTICIPANT\x10\x02*)\n\x0ePlaybackStatus\x12\x0b\n\x07PLAYING\x10\x00\x12\n\n\x06PAUSED\x10\x01*4\n\tEventType\x12\x08\n\x04PLAY\x10\x00\x12\t\n\x05PAUSE\x10\x01\x12\x08\n\x04SEEK\x10\x02\x12\x08\n\x04SKIP\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOMSTATUS']._serialized_start=41
  _globals['_ROOMSTATUS']._serialized_end=91
  _globals['_ROOMVISIBILITY']._serialized_start=93
  _globals['_ROOMVISIBILITY']._serialized_end=134
  _globals['_ROOMMEMBERROLE']._serialized_start=136
  _globals['_ROOMMEMBERROLE']._serialized_end=194
  _globals['_PLAYBACKSTATUS']._serialized_start=196
  _globals['_PLAYBACKSTATUS']._serialized_end=237
  _globals['_EVENTTYPE']._serialized_start=239
  _globals['_EVENTTYPE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
