# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protobuf import events_pb2 as protobuf_dot_events__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuf/events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRoomEvents = channel.unary_stream(
                '/ListeningParty.EventStreamService/StreamRoomEvents',
                request_serializer=protobuf_dot_events__pb2.StreamRoomEventsRequest.SerializeToString,
                response_deserializer=protobuf_dot_events__pb2.RoomEvent.FromString,
                _registered_method=True)
        self.StreamPlaybackEvents = channel.unary_stream(
                '/ListeningParty.EventStreamService/StreamPlaybackEvents',
                request_serializer=protobuf_dot_events__pb2.StreamPlaybackEventsRequest.SerializeToString,
                response_deserializer=protobuf_dot_events__pb2.PlaybackEvent.FromString,
                _registered_method=True)


class EventStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamRoomEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPlaybackEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRoomEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRoomEvents,
                    request_deserializer=protobuf_dot_events__pb2.StreamRoomEventsRequest.FromString,
                    response_serializer=protobuf_dot_events__pb2.RoomEvent.SerializeToString,
            ),
            'StreamPlaybackEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPlaybackEvents,
                    request_deserializer=protobuf_dot_events__pb2.StreamPlaybackEventsRequest.FromString,
                    response_serializer=protobuf_dot_events__pb2.PlaybackEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListeningParty.EventStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListeningParty.EventStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamRoomEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ListeningParty.EventStreamService/StreamRoomEvents',
            protobuf_dot_events__pb2.StreamRoomEventsRequest.SerializeToString,
            protobuf_dot_events__pb2.RoomEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPlaybackEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ListeningParty.EventStreamService/StreamPlaybackEvents',
            protobuf_dot_events__pb2.StreamPlaybackEventsRequest.SerializeToString,
            protobuf_dot_events__pb2.PlaybackEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventLogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogEvent = channel.unary_unary(
                '/ListeningParty.EventLogService/LogEvent',
                request_serializer=protobuf_dot_events__pb2.LogEventRequest.SerializeToString,
                response_deserializer=protobuf_dot_events__pb2.PlaybackEventLog.FromString,
                _registered_method=True)
        self.GetEventHistory = channel.unary_unary(
                '/ListeningParty.EventLogService/GetEventHistory',
                request_serializer=protobuf_dot_events__pb2.GetEventHistoryRequest.SerializeToString,
                response_deserializer=protobuf_dot_events__pb2.GetEventHistoryResponse.FromString,
                _registered_method=True)


class EventLogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventLogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.LogEvent,
                    request_deserializer=protobuf_dot_events__pb2.LogEventRequest.FromString,
                    response_serializer=protobuf_dot_events__pb2.PlaybackEventLog.SerializeToString,
            ),
            'GetEventHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventHistory,
                    request_deserializer=protobuf_dot_events__pb2.GetEventHistoryRequest.FromString,
                    response_serializer=protobuf_dot_events__pb2.GetEventHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListeningParty.EventLogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListeningParty.EventLogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventLogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.EventLogService/LogEvent',
            protobuf_dot_events__pb2.LogEventRequest.SerializeToString,
            protobuf_dot_events__pb2.PlaybackEventLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.EventLogService/GetEventHistory',
            protobuf_dot_events__pb2.GetEventHistoryRequest.SerializeToString,
            protobuf_dot_events__pb2.GetEventHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
