# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/playback.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protobuf/playback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import common_pb2 as protobuf_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protobuf/playback.proto\x12\x0eListeningParty\x1a\x15protobuf/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n\rPlaybackState\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x18\n\x10\x63urrent_track_id\x18\x02 \x01(\t\x12\x13\n\x0bposition_ms\x18\x03 \x01(\x05\x12.\n\x06status\x18\x04 \x01(\x0e\x32\x1e.ListeningParty.PlaybackStatus\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"E\n\x0bPlayRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x10\n\x08track_id\x18\x02 \x01(\t\x12\x13\n\x0bposition_ms\x18\x03 \x01(\x05\"\x1f\n\x0cPauseRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\"3\n\x0bSeekRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x13\n\x0bposition_ms\x18\x02 \x01(\x05\"\x1e\n\x0bSkipRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\"*\n\x17GetPlaybackStateRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\"7\n\x13SyncPlaybackRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t2\xd3\x03\n\x0fPlaybackService\x12\x42\n\x04Play\x12\x1b.ListeningParty.PlayRequest\x1a\x1d.ListeningParty.PlaybackState\x12\x44\n\x05Pause\x12\x1c.ListeningParty.PauseRequest\x1a\x1d.ListeningParty.PlaybackState\x12\x42\n\x04Seek\x12\x1b.ListeningParty.SeekRequest\x1a\x1d.ListeningParty.PlaybackState\x12\x42\n\x04Skip\x12\x1b.ListeningParty.SkipRequest\x1a\x1d.ListeningParty.PlaybackState\x12Z\n\x10GetPlaybackState\x12\'.ListeningParty.GetPlaybackStateRequest\x1a\x1d.ListeningParty.PlaybackState\x12R\n\x0cSyncPlayback\x12#.ListeningParty.SyncPlaybackRequest\x1a\x1d.ListeningParty.PlaybackStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.playback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYBACKSTATE']._serialized_start=100
  _globals['_PLAYBACKSTATE']._serialized_end=275
  _globals['_PLAYREQUEST']._serialized_start=277
  _globals['_PLAYREQUEST']._serialized_end=346
  _globals['_PAUSEREQUEST']._serialized_start=348
  _globals['_PAUSEREQUEST']._serialized_end=379
  _globals['_SEEKREQUEST']._serialized_start=381
  _globals['_SEEKREQUEST']._serialized_end=432
  _globals['_SKIPREQUEST']._serialized_start=434
  _globals['_SKIPREQUEST']._serialized_end=464
  _globals['_GETPLAYBACKSTATEREQUEST']._serialized_start=466
  _globals['_GETPLAYBACKSTATEREQUEST']._serialized_end=508
  _globals['_SYNCPLAYBACKREQUEST']._serialized_start=510
  _globals['_SYNCPLAYBACKREQUEST']._serialized_end=565
  _globals['_PLAYBACKSERVICE']._serialized_start=568
  _globals['_PLAYBACKSERVICE']._serialized_end=1035
# @@protoc_insertion_point(module_scope)
