# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protobuf import playback_pb2 as protobuf_dot_playback__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuf/playback_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlaybackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Play = channel.unary_unary(
                '/ListeningParty.PlaybackService/Play',
                request_serializer=protobuf_dot_playback__pb2.PlayRequest.SerializeToString,
                response_deserializer=protobuf_dot_playback__pb2.PlaybackState.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/ListeningParty.PlaybackService/Pause',
                request_serializer=protobuf_dot_playback__pb2.PauseRequest.SerializeToString,
                response_deserializer=protobuf_dot_playback__pb2.PlaybackState.FromString,
                _registered_method=True)
        self.Seek = channel.unary_unary(
                '/ListeningParty.PlaybackService/Seek',
                request_serializer=protobuf_dot_playback__pb2.SeekRequest.SerializeToString,
                response_deserializer=protobuf_dot_playback__pb2.PlaybackState.FromString,
                _registered_method=True)
        self.Skip = channel.unary_unary(
                '/ListeningParty.PlaybackService/Skip',
                request_serializer=protobuf_dot_playback__pb2.SkipRequest.SerializeToString,
                response_deserializer=protobuf_dot_playback__pb2.PlaybackState.FromString,
                _registered_method=True)
        self.GetPlaybackState = channel.unary_unary(
                '/ListeningParty.PlaybackService/GetPlaybackState',
                request_serializer=protobuf_dot_playback__pb2.GetPlaybackStateRequest.SerializeToString,
                response_deserializer=protobuf_dot_playback__pb2.PlaybackState.FromString,
                _registered_method=True)
        self.SyncPlayback = channel.unary_unary(
                '/ListeningParty.PlaybackService/SyncPlayback',
                request_serializer=protobuf_dot_playback__pb2.SyncPlaybackRequest.SerializeToString,
                response_deserializer=protobuf_dot_playback__pb2.PlaybackState.FromString,
                _registered_method=True)


class PlaybackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Play(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Seek(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Skip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaybackState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPlayback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaybackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Play': grpc.unary_unary_rpc_method_handler(
                    servicer.Play,
                    request_deserializer=protobuf_dot_playback__pb2.PlayRequest.FromString,
                    response_serializer=protobuf_dot_playback__pb2.PlaybackState.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=protobuf_dot_playback__pb2.PauseRequest.FromString,
                    response_serializer=protobuf_dot_playback__pb2.PlaybackState.SerializeToString,
            ),
            'Seek': grpc.unary_unary_rpc_method_handler(
                    servicer.Seek,
                    request_deserializer=protobuf_dot_playback__pb2.SeekRequest.FromString,
                    response_serializer=protobuf_dot_playback__pb2.PlaybackState.SerializeToString,
            ),
            'Skip': grpc.unary_unary_rpc_method_handler(
                    servicer.Skip,
                    request_deserializer=protobuf_dot_playback__pb2.SkipRequest.FromString,
                    response_serializer=protobuf_dot_playback__pb2.PlaybackState.SerializeToString,
            ),
            'GetPlaybackState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaybackState,
                    request_deserializer=protobuf_dot_playback__pb2.GetPlaybackStateRequest.FromString,
                    response_serializer=protobuf_dot_playback__pb2.PlaybackState.SerializeToString,
            ),
            'SyncPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncPlayback,
                    request_deserializer=protobuf_dot_playback__pb2.SyncPlaybackRequest.FromString,
                    response_serializer=protobuf_dot_playback__pb2.PlaybackState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListeningParty.PlaybackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListeningParty.PlaybackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaybackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Play(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.PlaybackService/Play',
            protobuf_dot_playback__pb2.PlayRequest.SerializeToString,
            protobuf_dot_playback__pb2.PlaybackState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.PlaybackService/Pause',
            protobuf_dot_playback__pb2.PauseRequest.SerializeToString,
            protobuf_dot_playback__pb2.PlaybackState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Seek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.PlaybackService/Seek',
            protobuf_dot_playback__pb2.SeekRequest.SerializeToString,
            protobuf_dot_playback__pb2.PlaybackState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Skip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.PlaybackService/Skip',
            protobuf_dot_playback__pb2.SkipRequest.SerializeToString,
            protobuf_dot_playback__pb2.PlaybackState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaybackState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.PlaybackService/GetPlaybackState',
            protobuf_dot_playback__pb2.GetPlaybackStateRequest.SerializeToString,
            protobuf_dot_playback__pb2.PlaybackState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.PlaybackService/SyncPlayback',
            protobuf_dot_playback__pb2.SyncPlaybackRequest.SerializeToString,
            protobuf_dot_playback__pb2.PlaybackState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
