# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protobuf import queue_pb2 as protobuf_dot_queue__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuf/queue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddToQueue = channel.unary_unary(
                '/ListeningParty.QueueService/AddToQueue',
                request_serializer=protobuf_dot_queue__pb2.AddToQueueRequest.SerializeToString,
                response_deserializer=protobuf_dot_queue__pb2.RoomQueueItem.FromString,
                _registered_method=True)
        self.RemoveFromQueue = channel.unary_unary(
                '/ListeningParty.QueueService/RemoveFromQueue',
                request_serializer=protobuf_dot_queue__pb2.RemoveFromQueueRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetQueue = channel.unary_unary(
                '/ListeningParty.QueueService/GetQueue',
                request_serializer=protobuf_dot_queue__pb2.GetQueueRequest.SerializeToString,
                response_deserializer=protobuf_dot_queue__pb2.GetQueueResponse.FromString,
                _registered_method=True)
        self.ClearQueue = channel.unary_unary(
                '/ListeningParty.QueueService/ClearQueue',
                request_serializer=protobuf_dot_queue__pb2.ClearQueueRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class QueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddToQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddToQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToQueue,
                    request_deserializer=protobuf_dot_queue__pb2.AddToQueueRequest.FromString,
                    response_serializer=protobuf_dot_queue__pb2.RoomQueueItem.SerializeToString,
            ),
            'RemoveFromQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromQueue,
                    request_deserializer=protobuf_dot_queue__pb2.RemoveFromQueueRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueue,
                    request_deserializer=protobuf_dot_queue__pb2.GetQueueRequest.FromString,
                    response_serializer=protobuf_dot_queue__pb2.GetQueueResponse.SerializeToString,
            ),
            'ClearQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearQueue,
                    request_deserializer=protobuf_dot_queue__pb2.ClearQueueRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListeningParty.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListeningParty.QueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddToQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.QueueService/AddToQueue',
            protobuf_dot_queue__pb2.AddToQueueRequest.SerializeToString,
            protobuf_dot_queue__pb2.RoomQueueItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.QueueService/RemoveFromQueue',
            protobuf_dot_queue__pb2.RemoveFromQueueRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.QueueService/GetQueue',
            protobuf_dot_queue__pb2.GetQueueRequest.SerializeToString,
            protobuf_dot_queue__pb2.GetQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.QueueService/ClearQueue',
            protobuf_dot_queue__pb2.ClearQueueRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
