# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/queue.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protobuf/queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protobuf/queue.proto\x12\x0eListeningParty\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x01\n\rRoomQueueItem\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x10\n\x08track_id\x18\x03 \x01(\t\x12\x10\n\x08\x61\x64\x64\x65\x64_by\x18\x04 \x01(\t\x12,\n\x08\x61\x64\x64\x65\x64_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"G\n\x11\x41\x64\x64ToQueueRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x10\n\x08track_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\";\n\x16RemoveFromQueueRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x10\n\x08track_id\x18\x02 \x01(\t\"\"\n\x0fGetQueueRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\"@\n\x10GetQueueResponse\x12,\n\x05items\x18\x01 \x03(\x0b\x32\x1d.ListeningParty.RoomQueueItem\"$\n\x11\x43learQueueRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t2\xc9\x02\n\x0cQueueService\x12N\n\nAddToQueue\x12!.ListeningParty.AddToQueueRequest\x1a\x1d.ListeningParty.RoomQueueItem\x12Q\n\x0fRemoveFromQueue\x12&.ListeningParty.RemoveFromQueueRequest\x1a\x16.google.protobuf.Empty\x12M\n\x08GetQueue\x12\x1f.ListeningParty.GetQueueRequest\x1a .ListeningParty.GetQueueResponse\x12G\n\nClearQueue\x12!.ListeningParty.ClearQueueRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOMQUEUEITEM']._serialized_start=103
  _globals['_ROOMQUEUEITEM']._serialized_end=235
  _globals['_ADDTOQUEUEREQUEST']._serialized_start=237
  _globals['_ADDTOQUEUEREQUEST']._serialized_end=308
  _globals['_REMOVEFROMQUEUEREQUEST']._serialized_start=310
  _globals['_REMOVEFROMQUEUEREQUEST']._serialized_end=369
  _globals['_GETQUEUEREQUEST']._serialized_start=371
  _globals['_GETQUEUEREQUEST']._serialized_end=405
  _globals['_GETQUEUERESPONSE']._serialized_start=407
  _globals['_GETQUEUERESPONSE']._serialized_end=471
  _globals['_CLEARQUEUEREQUEST']._serialized_start=473
  _globals['_CLEARQUEUEREQUEST']._serialized_end=509
  _globals['_QUEUESERVICE']._serialized_start=512
  _globals['_QUEUESERVICE']._serialized_end=841
# @@protoc_insertion_point(module_scope)
