# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protobuf import room_pb2 as protobuf_dot_room__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuf/room_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoomServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRoom = channel.unary_unary(
                '/ListeningParty.RoomService/CreateRoom',
                request_serializer=protobuf_dot_room__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=protobuf_dot_room__pb2.Room.FromString,
                _registered_method=True)
        self.GetRoom = channel.unary_unary(
                '/ListeningParty.RoomService/GetRoom',
                request_serializer=protobuf_dot_room__pb2.GetRoomRequest.SerializeToString,
                response_deserializer=protobuf_dot_room__pb2.Room.FromString,
                _registered_method=True)
        self.UpdateRoom = channel.unary_unary(
                '/ListeningParty.RoomService/UpdateRoom',
                request_serializer=protobuf_dot_room__pb2.UpdateRoomRequest.SerializeToString,
                response_deserializer=protobuf_dot_room__pb2.Room.FromString,
                _registered_method=True)
        self.DeleteRoom = channel.unary_unary(
                '/ListeningParty.RoomService/DeleteRoom',
                request_serializer=protobuf_dot_room__pb2.DeleteRoomRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListRooms = channel.unary_unary(
                '/ListeningParty.RoomService/ListRooms',
                request_serializer=protobuf_dot_room__pb2.ListRoomsRequest.SerializeToString,
                response_deserializer=protobuf_dot_room__pb2.ListRoomsResponse.FromString,
                _registered_method=True)
        self.JoinRoom = channel.unary_unary(
                '/ListeningParty.RoomService/JoinRoom',
                request_serializer=protobuf_dot_room__pb2.JoinRoomRequest.SerializeToString,
                response_deserializer=protobuf_dot_room__pb2.Room.FromString,
                _registered_method=True)
        self.LeaveRoom = channel.unary_unary(
                '/ListeningParty.RoomService/LeaveRoom',
                request_serializer=protobuf_dot_room__pb2.LeaveRoomRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.InviteToRoom = channel.unary_unary(
                '/ListeningParty.RoomService/InviteToRoom',
                request_serializer=protobuf_dot_room__pb2.InviteToRoomRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.KickFromRoom = channel.unary_unary(
                '/ListeningParty.RoomService/KickFromRoom',
                request_serializer=protobuf_dot_room__pb2.KickFromRoomRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class RoomServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteToRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KickFromRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=protobuf_dot_room__pb2.CreateRoomRequest.FromString,
                    response_serializer=protobuf_dot_room__pb2.Room.SerializeToString,
            ),
            'GetRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoom,
                    request_deserializer=protobuf_dot_room__pb2.GetRoomRequest.FromString,
                    response_serializer=protobuf_dot_room__pb2.Room.SerializeToString,
            ),
            'UpdateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRoom,
                    request_deserializer=protobuf_dot_room__pb2.UpdateRoomRequest.FromString,
                    response_serializer=protobuf_dot_room__pb2.Room.SerializeToString,
            ),
            'DeleteRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoom,
                    request_deserializer=protobuf_dot_room__pb2.DeleteRoomRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRooms,
                    request_deserializer=protobuf_dot_room__pb2.ListRoomsRequest.FromString,
                    response_serializer=protobuf_dot_room__pb2.ListRoomsResponse.SerializeToString,
            ),
            'JoinRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinRoom,
                    request_deserializer=protobuf_dot_room__pb2.JoinRoomRequest.FromString,
                    response_serializer=protobuf_dot_room__pb2.Room.SerializeToString,
            ),
            'LeaveRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveRoom,
                    request_deserializer=protobuf_dot_room__pb2.LeaveRoomRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'InviteToRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteToRoom,
                    request_deserializer=protobuf_dot_room__pb2.InviteToRoomRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'KickFromRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.KickFromRoom,
                    request_deserializer=protobuf_dot_room__pb2.KickFromRoomRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListeningParty.RoomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListeningParty.RoomService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoomService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomService/CreateRoom',
            protobuf_dot_room__pb2.CreateRoomRequest.SerializeToString,
            protobuf_dot_room__pb2.Room.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomService/GetRoom',
            protobuf_dot_room__pb2.GetRoomRequest.SerializeToString,
            protobuf_dot_room__pb2.Room.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomService/UpdateRoom',
            protobuf_dot_room__pb2.UpdateRoomRequest.SerializeToString,
            protobuf_dot_room__pb2.Room.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomService/DeleteRoom',
            protobuf_dot_room__pb2.DeleteRoomRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomService/ListRooms',
            protobuf_dot_room__pb2.ListRoomsRequest.SerializeToString,
            protobuf_dot_room__pb2.ListRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomService/JoinRoom',
            protobuf_dot_room__pb2.JoinRoomRequest.SerializeToString,
            protobuf_dot_room__pb2.Room.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomService/LeaveRoom',
            protobuf_dot_room__pb2.LeaveRoomRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InviteToRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomService/InviteToRoom',
            protobuf_dot_room__pb2.InviteToRoomRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KickFromRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomService/KickFromRoom',
            protobuf_dot_room__pb2.KickFromRoomRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
