# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protobuf import streaming_pb2 as protobuf_dot_streaming__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuf/streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoomStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinRoomStream = channel.unary_unary(
                '/ListeningParty.RoomStreamService/JoinRoomStream',
                request_serializer=protobuf_dot_streaming__pb2.JoinRoomStreamRequest.SerializeToString,
                response_deserializer=protobuf_dot_streaming__pb2.RoomStreamSnapshot.FromString,
                _registered_method=True)
        self.StreamRoomUpdates = channel.unary_stream(
                '/ListeningParty.RoomStreamService/StreamRoomUpdates',
                request_serializer=protobuf_dot_streaming__pb2.StreamRoomUpdatesRequest.SerializeToString,
                response_deserializer=protobuf_dot_streaming__pb2.RoomStreamUpdate.FromString,
                _registered_method=True)


class RoomStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinRoomStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRoomUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinRoomStream': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinRoomStream,
                    request_deserializer=protobuf_dot_streaming__pb2.JoinRoomStreamRequest.FromString,
                    response_serializer=protobuf_dot_streaming__pb2.RoomStreamSnapshot.SerializeToString,
            ),
            'StreamRoomUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRoomUpdates,
                    request_deserializer=protobuf_dot_streaming__pb2.StreamRoomUpdatesRequest.FromString,
                    response_serializer=protobuf_dot_streaming__pb2.RoomStreamUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListeningParty.RoomStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListeningParty.RoomStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoomStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinRoomStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.RoomStreamService/JoinRoomStream',
            protobuf_dot_streaming__pb2.JoinRoomStreamRequest.SerializeToString,
            protobuf_dot_streaming__pb2.RoomStreamSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRoomUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ListeningParty.RoomStreamService/StreamRoomUpdates',
            protobuf_dot_streaming__pb2.StreamRoomUpdatesRequest.SerializeToString,
            protobuf_dot_streaming__pb2.RoomStreamUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
