# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protobuf import streaming_pb2 as protobuf_dot_streaming__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuf/streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SyncServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendHostCommand = channel.stream_stream(
                '/ListeningParty.SyncService/SendHostCommand',
                request_serializer=protobuf_dot_streaming__pb2.HostCommand.SerializeToString,
                response_deserializer=protobuf_dot_streaming__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.TimingSync = channel.unary_unary(
                '/ListeningParty.SyncService/TimingSync',
                request_serializer=protobuf_dot_streaming__pb2.SyncRequest.SerializeToString,
                response_deserializer=protobuf_dot_streaming__pb2.SyncReply.FromString,
                _registered_method=True)
        self.MemberSync = channel.stream_stream(
                '/ListeningParty.SyncService/MemberSync',
                request_serializer=protobuf_dot_streaming__pb2.MemberStatus.SerializeToString,
                response_deserializer=protobuf_dot_streaming__pb2.ServerBroadcast.FromString,
                _registered_method=True)


class SyncServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendHostCommand(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TimingSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemberSync(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendHostCommand': grpc.stream_stream_rpc_method_handler(
                    servicer.SendHostCommand,
                    request_deserializer=protobuf_dot_streaming__pb2.HostCommand.FromString,
                    response_serializer=protobuf_dot_streaming__pb2.ServerResponse.SerializeToString,
            ),
            'TimingSync': grpc.unary_unary_rpc_method_handler(
                    servicer.TimingSync,
                    request_deserializer=protobuf_dot_streaming__pb2.SyncRequest.FromString,
                    response_serializer=protobuf_dot_streaming__pb2.SyncReply.SerializeToString,
            ),
            'MemberSync': grpc.stream_stream_rpc_method_handler(
                    servicer.MemberSync,
                    request_deserializer=protobuf_dot_streaming__pb2.MemberStatus.FromString,
                    response_serializer=protobuf_dot_streaming__pb2.ServerBroadcast.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListeningParty.SyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListeningParty.SyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendHostCommand(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ListeningParty.SyncService/SendHostCommand',
            protobuf_dot_streaming__pb2.HostCommand.SerializeToString,
            protobuf_dot_streaming__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TimingSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListeningParty.SyncService/TimingSync',
            protobuf_dot_streaming__pb2.SyncRequest.SerializeToString,
            protobuf_dot_streaming__pb2.SyncReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemberSync(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ListeningParty.SyncService/MemberSync',
            protobuf_dot_streaming__pb2.MemberStatus.SerializeToString,
            protobuf_dot_streaming__pb2.ServerBroadcast.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
