# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/track.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protobuf/track.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protobuf/track.proto\x12\x0eListeningParty\"`\n\x05Track\x12\x10\n\x08track_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x05\"#\n\x0fGetTrackRequest\x12\x10\n\x08track_id\x18\x01 \x01(\t\"K\n\x13SearchTracksRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\"V\n\x14SearchTracksResponse\x12%\n\x06tracks\x18\x01 \x03(\x0b\x32\x15.ListeningParty.Track\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xad\x01\n\x0cTrackService\x12\x42\n\x08GetTrack\x12\x1f.ListeningParty.GetTrackRequest\x1a\x15.ListeningParty.Track\x12Y\n\x0cSearchTracks\x12#.ListeningParty.SearchTracksRequest\x1a$.ListeningParty.SearchTracksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.track_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACK']._serialized_start=40
  _globals['_TRACK']._serialized_end=136
  _globals['_GETTRACKREQUEST']._serialized_start=138
  _globals['_GETTRACKREQUEST']._serialized_end=173
  _globals['_SEARCHTRACKSREQUEST']._serialized_start=175
  _globals['_SEARCHTRACKSREQUEST']._serialized_end=250
  _globals['_SEARCHTRACKSRESPONSE']._serialized_start=252
  _globals['_SEARCHTRACKSRESPONSE']._serialized_end=338
  _globals['_TRACKSERVICE']._serialized_start=341
  _globals['_TRACKSERVICE']._serialized_end=514
# @@protoc_insertion_point(module_scope)
