# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ytmusic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ytmusic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rytmusic.proto\x12\x07ytmusic\"=\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"\xba\x02\n\x05Track\x12\x10\n\x08track_id\x18\x01 \x01(\t\x12\x12\n\ntrack_name\x18\x02 \x01(\t\x12\x13\n\x0b\x61rtist_name\x18\x03 \x01(\t\x12\x17\n\nalbum_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x64uration\x18\x05 \x01(\x05H\x01\x88\x01\x01\x12\x0e\n\x06genres\x18\x06 \x03(\t\x12\x16\n\timage_url\x18\x07 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0bpreview_url\x18\x08 \x01(\tH\x03\x88\x01\x01\x12\x10\n\x08video_id\x18\t \x01(\t\x12\x11\n\tlisteners\x18\n \x01(\x03\x12\x11\n\tplaycount\x18\x0b \x01(\x03\x12\x12\n\npopularity\x18\x0c \x01(\x05\x42\r\n\x0b_album_nameB\x0b\n\t_durationB\x0c\n\n_image_urlB\x0e\n\x0c_preview_url\"\xa5\x01\n\x0eSearchResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x1e\n\x06tracks\x18\x03 \x03(\x0b\x32\x0e.ytmusic.Track\x12\r\n\x05total\x18\x04 \x01(\x05\x12\r\n\x05limit\x18\x05 \x01(\x05\x12\x0e\n\x06offset\x18\x06 \x01(\x05\x12\x14\n\x07message\x18\x07 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"8\n\x15RecommendationRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"\x8e\x01\n\x16RecommendationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x1e\n\x06tracks\x18\x03 \x03(\x0b\x32\x0e.ytmusic.Track\x12\r\n\x05total\x18\x04 \x01(\x05\x12\x14\n\x07message\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message2\xa8\x01\n\x0eYTMusicService\x12?\n\x0cSearchTracks\x12\x16.ytmusic.SearchRequest\x1a\x17.ytmusic.SearchResponse\x12U\n\x12GetRecommendations\x12\x1e.ytmusic.RecommendationRequest\x1a\x1f.ytmusic.RecommendationResponseB1Z/github.com/bluppi/bluppi-backend-v2/pkg/ytmusicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ytmusic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/bluppi/bluppi-backend-v2/pkg/ytmusic'
  _globals['_SEARCHREQUEST']._serialized_start=26
  _globals['_SEARCHREQUEST']._serialized_end=87
  _globals['_TRACK']._serialized_start=90
  _globals['_TRACK']._serialized_end=404
  _globals['_SEARCHRESPONSE']._serialized_start=407
  _globals['_SEARCHRESPONSE']._serialized_end=572
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=574
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=630
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=633
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=775
  _globals['_YTMUSICSERVICE']._serialized_start=778
  _globals['_YTMUSICSERVICE']._serialized_end=946
# @@protoc_insertion_point(module_scope)
