tunnel: c2086af3-2bc2-4a86-9276-545eb42f6ec1
credentials-file: /etc/cloudflared/c2086af3-2bc2-4a86-9276-545eb42f6ec1.json

ha-connections: 1
protocol: http2

ingress:
  # 1. Android Deeplinks & Web profiles
  - hostname: bluppi.saikat.in
    path: /(u|invite|\.well-known)/.*
    service: http://bluppi-audio-api:8000

  # 2. Dedicated REST API
  - hostname: bluppi.saikat.in
    path: /api/rest/.*
    service: http://bluppi-audio-api:8000

  # 3. gRPC Gateway (REST API v2)
  - hostname: bluppi.saikat.in
    path: /api/v2/.*
    service: h2c://bluppi-gateway:50050
    originRequest:
      noTLSVerify: true
      http2Origin: true

  # 4. Pure gRPC API (Catch-All)
  - hostname: bluppi.saikat.in
    service: https://bluppi-api:50051
    originRequest:
      noTLSVerify: true
      http2Origin: true

  - service: http_status:404
